services:

  mysqldb:
    image: mysql:8.0
    volumes:
      - db_data_mysql_cas:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: emmet
      MYSQL_USER: cas
      MYSQL_PASSWORD: cas
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: cas
      MONGO_INITDB_ROOT_PASSWORD: cas
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./sbdi/data/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:z
      - db_data_mongo_cas:/data/db
    ports:
      - 27017:27017

  cas:
    depends_on:
      - mysqldb
      - mongodb
    image: sbdi/cas-dev
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - ./sbdi/data/config/application.yml:/data/cas/config/application.yml
      - ./sbdi/data/config/pwe.properties:/data/cas/config/pwe.properties
      - ./sbdi/data/config/log4j2.xml:/data/cas/config/log4j2.xml

volumes:
  db_data_mysql_cas:
  db_data_mongo_cas:
  #db_data_cas_empty:
  #db_data_mongo_cas_empty:
